# Generated by Django 3.1.2 on 2020-10-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_applicants_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicants_model',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('TRANSGENDER', 'TRANSGENDER')], default=('MALE', 'MALE'), max_length=255),
        ),
        migrations.AlterField(
            model_name='applicants_model',
            name='package',
            field=models.CharField(choices=[('Training By Hatchback(45 days)', 'Training By Hatchback(45 days)'), ('Training By Hatchback(30 days)', 'Training By Hatchback(30 days)'), ('Training By SUV(30 days)', 'Training By SUV(30 days)'), ('Training By SUV(45 days)', 'Training By SUV(45 days)')], default=('Training By Hatchback(45 days)', 'Training By Hatchback(45 days)'), max_length=255),
        ),
        migrations.AlterField(
            model_name='applicants_model',
            name='timing',
            field=models.CharField(choices=[('09:00AM-10:00AM', '09:00AM-10:00AM'), ('10:00AM-11:00AM', '10:00AM-11:00AM'), ('11:00AM-12:00PM', '11:00AM-12:00PM'), ('12:00PM-01:00PM', '12:00AM-01:00PM'), ('01:00PM-02:00PM', '01:00AM-02:00PM'), ('02:00PM-03:00PM', '02:00AM-03:00PM'), ('03:00PM-04:00PM', '03:00AM-04:00PM'), ('04:00PM-05:00PM', '04:00AM-05:00PM'), ('05:00PM-06:00PM', '05:00AM-06:00PM')], default=('09:00AM-10:00AM', '09:00AM-10:00AM'), max_length=255),
        ),
    ]
